### ISSUE TITLE
Bug in NGram extraction

### ISSUE THREAD

**Issue by zdeseb** [pdonald/language-detection#1]
Hello,
I noticed, that detection didn't function correctly for example for text "Výsledky kvalifikace slopestylu na ZOH v Soči" which is "cs" language but this component returned "sk".

I tried detection by original Java library with the same language profiles and I got correct result.

So after some debugging I found, that ExtractNGrams() returns single character NGrams only.

In my opinion, there is error in LanguageDetector.cs in line 364, there is
<b>return buffer.ToString(buffer.Length - n, buffer.Length - n);</b>
but should be
<b>return buffer.ToString(buffer.Length - n, n);</b>

I look forward to new Nuget package version :-)

Regards,
Zdenek

**Comment by pdonald** [comment]
Thanks!

https://www.nuget.org/packages/LanguageDetection/1.1.1
https://github.com/pdonald/language-detection/releases/tag/v1.1.1

**Comment by zdeseb** [comment]
Pretty fast, thanks :-)
