### ISSUE TITLE
Shorter texts & algorithm behavior

### ISSUE THREAD

**Issue by zdeseb** [pdonald/language-detection#2]
Hello,
I am facing following problem:

When I have text which is (from statistical point of view) for example 80% in language A and 20% in language B (A and B are related languages). The algorithm internally iterates until MaxIterations or ConvergenceThreshold is reached.

For short texts (with for example 95 relevant NGrams) many iterations together with high ConvergenceThreshold results into blurring differences and result with only one language with 0.9999 probability.

I think that algorithm should take into account NGram count to not multiply differences between languages indefinitely.

Of course this kind of modification is not backward compatible (and compatible with original Java library), would require intensive testing and probably is not needed by other users.

<b>So I suggest to put out MaxIterations and ConvergenceThreshold as parameters which can be changed by programmer.</b> It can be for example property of LanguageDetector or optional parameter of Detect and DetectAll methods.

<i>To have concrete example, you can try to detect language of text "Výsledky kola švýcarské hokejové ligy" with default ConvergenceThreshold and than with value lowered for example to 0.9</i>

Regards,
Zdenek

**Comment by zdeseb** [comment]
Hello,
thanks for change in source code.

Issue_2 test code can be for example something like:
<b>...</b>
detector.AddAllLanguages();
<b>Assert.AreEqual(1, detector.DetectAll(text).Count());</b>
<b>...</b>
detector.ConvergenceThreshold = 0.9;
detector.AddAllLanguages();
<b>Assert.AreEqual(2, detector.DetectAll(text).Count());</b>

That should correspond the issue idea.

Could you please create Nuget package with new version?

Thanks,
Zdenek

**Comment by pdonald** [comment]
I added `detector.RandomSeed = 1` everywhere in unit tests because without it the test would sometimes pass and sometimes fail.

The test is failing with the value `0.9`. Can you give me another value or a different text?

**Comment by zdeseb** [comment]
You can add following MaxIterations setting (to get Count == 2):
detector.ConvergenceThreshold = 0.9;
<b>detector.MaxIterations = 50;</b>

But you have to remove (or change "cs" to "sk") following Assert, it will never be true:
<strike><b>Assert.AreEqual("cs", detector.Detect(text));</b></strike>

The idea is, that with change of ConvergenceThreshold and MaxIterations values you get more detailed info which includes languages that are rejected by default setting. (not to totally reverse statistical profile)

**Comment by pdonald** [comment]
Thanks!

https://www.nuget.org/packages/LanguageDetection/1.2.0
https://github.com/pdonald/language-detection/releases/tag/v1.2.0
