### ISSUE TITLE
Threadsafe?

### ISSUE THREAD

**Issue by RobertDM** [pdonald/language-detection#3]
Is the LanguageDetector object thread safe?

Would be convenient to allocate a single instance for use across an app.

**Comment by pdonald** [comment]
`Detect` and `DetectAll` do not modify the object state. As long as you don't change any properties and add languages, you can use a single instance.

**Comment by RobertDM** [comment]
Appreciate the quick response!  After some more testing though, I decided that the false positive rate for short text was more than I could accept.  Example:  The following string is identified as Norwegian: "Funny , handsome, drama free , like to travel, like to eat, laid back"

**Comment by TechnikEmpire** [comment]
@RobertDM I think maybe you should check that again. When I run your test, it correctly determines the language to be english.

**Comment by TechnikEmpire** [comment]
@pdonald I ported your project to .NET Standard 2.0, but I blew away the whole custom build/binarization of the embedded resources and opted to embed them straight and json decode them within the main assembly. It was a pain in the neck to replicate that functionality for me, so I don't care if my dll is 1.1 megs larger.

Let me know if you want me to submit a PR. Thanks for your work.
