### ISSUE TITLE
Source of language corpus

### ISSUE THREAD

**Issue by DonaldTsang** [pdonald/language-detection#6]
Where is the source text dataset for the Ngrams of those 110 languages? Would like to see if it is different from https://github.com/wooorm/franc/issues/78 usage of UDHR, and if it is more accurate than them.

**Comment by pdonald** [comment]
This project is a fork of this project: https://github.com/shuyo/language-detection/tree/master/profiles

There https://github.com/shuyo/language-detection/blob/wiki/ProjectHome.md it says

> Generate language profiles from Wikipedia abstract xml

**Comment by DonaldTsang** [comment]
@pdonald how do they extract data from Wikipedia?
